#!/bin/bash
set -e

source ${CHARM_DIR}/hooks/common.sh

###############################################################################
# Remove juju specific database configuration
###############################################################################
rm -f ${UNIT_DIR}/juju_settings.py
python ${UNIT_DIR}/manage.py syncdb --noinput
