#!/bin/bash
set -e

source $(dirname "$0")/common.sh

###############################################################################
# Remove juju specific database configuration
###############################################################################
rm -f ${UNIT_DIR}/juju_settings.py
python ${UNIT_DIR}/manage.py syncdb --noinput
